server:
  port: 8080


distribution:
  cacheSize: 2000
  poolSize: 4
  # host|port|queueManager|channel|ccsid|queueName|minConcurrency|maxConcurrency|keepAliveSeconds|queueCapacity|threadNamePrefix
  otherInputQueue:
  # host|port|username|password|virtualHost|cacheMode|channelCacheSize|connectionCacheSize|connectionLimit|minConcurrency|maxConcurrency|prefetchCount|keepAliveSeconds|queueCapacity|threadNamePrefix|queues
  otherRabbitInputQueue:
  # dir|fileFilter|periodic(s)|maxMessagesPerPoll|minConcurrency|maxConcurrency|keepAliveSeconds|queueCcpacity|threadNamePrefix
  otherDirectorInput:
  # hostName|port|queueManager|channel|ccsid|sessionCacheSize
  otherOutputQueue:
  # host|port|username|password|virtualHost|cacheModel|channelCacheSize|connectionCacheSize|connectionLimit
  rabbitOtherOutputQueue:
  conditionMutualExclusion: true
  # 优先级第一 map key:dxpid, value: 队列名称 如: {DXPENT0000011951: DXP_11951_ENT},
  # 加"|数字" 是 otherOutputQueue 中的索引, 加"||数字"是 rabbitOtherOutputQueue中的索引,rabbitOtherOutputQueue为第一个,
  # 加|||则前面为输入目录名,直接把数据写入到相应目录
  dxpidDistribution: {}
  # 优先级第二 map key:msgtype, value: 队列名称 如: {CEB312Message: DXP_11951_ENT}
  msgtypeDistribution: {}
  # 优先级第三 map key:dxpid, value: 队列名称 如: {DXPENT0000011951: DXP_11951_ENT},
  # 加"|数字" 是 otherOutputQueue 中的索引, 加"||数字"是 rabbitOtherOutputQueue中的索引,rabbitOtherOutputQueue为第一个,
  # 加|||则前面为输入目录名,直接把数据写入到相应目录
  senderIdDistribution: {}
  # 优先级第四 map key: 队列名称, value: 比重 如: {GGFW_TO_ENT: 1, GGFW_TO_ENT_INVT: 1}
  percentageDistribution: {}
  # 前面四个没有，才执行最后一个 列表格式，随机分发
  randomDistribution:
  # 所有没有区配到，就转发到默认队列
  # 加"|数字" 是 otherOutputQueue 中的索引, 加"||数字"是 rabbitOtherOutputQueue中的索引,rabbitOtherOutputQueue为第一个,
  # 加|||则前面为输入目录名,直接把数据写入到相应目录
  defaultQueue: GGFW_TO_ENT
  filePrefix: FILE_RECEIVE_
  fileSuffix: .xml
  # 存文件的时候是否解dxp封装
  unWrap: true

logging:
  config: classpath:logback-spring.xml
